### ISSUE TITLE
Add linters as like Libplanet

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet-explorer#13]
libplanet-explorer doesn't have any linter yet. it would be better if we add [StyleCop](https://www.nuget.org/packages/StyleCop/) and [Menees.Analyzers](https://www.nuget.org/packages/Menees.Analyzers/).

**Comment by limebell** [comment]
Is this resolved? @earlbread

**Comment by earlbread** [comment]
Yes, it is resolved.
