### ISSUE TITLE
Portable pwsh shebang

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet-explorer#17]
Currently `run.ps1` and `build.ps1` aren't compatible with bash on Ubuntu.

```
~/libplanet-explorer $ ./build.ps1 
/usr/local/bin/pwsh: command not found
```

**Comment by longfin** [comment]
I think that we can use [`env`](https://en.wikipedia.org/wiki/Env) command for portability.

**Comment by ipdae** [comment]
i'll try this issue.
